drop table if exists appointment  cascade;
drop table if exists dentist_names  cascade;


create table appointment (
                             id bigint generated by default as identity,
                             date binary(255),
                             is_available boolean,
                             period varchar(255),
                             dentist_id bigint,
                             primary key (id)
);

create table dentist_names (
                               id bigint generated by default as identity,
                               name varchar(255),
                               primary key (id)
);

alter table if exists appointment
    add constraint FK
        foreign key (dentist_id)
            references dentist_names;

insert into dentist_names (name) values ('Juri Reedik');
insert into dentist_names (name) values ('Urmas Rebane');
insert into dentist_names (name) values ('Andre Trudnikov');
insert into dentist_names (name) values ('Arkadi Popov');
insert into dentist_names (name) values ('Mari-Liis Tamm');
insert into dentist_names (name) values ('Anne Õim');


